BNS

INSERT INTO '''STRDBA'''.apirequest
(apirequestid, apino, '''filter''', typename, description, example, required, apimasterid, objectname, isarray)
VALUES
((select max(apirequestid) +1 from apirequest), 1, 'serviceBillingCreditTerm', 'Integer', 'จำนวนวันที่ครบกำหนด',  10, 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +2 from apirequest), 2, 'serviceBillingTotal', 'Decimal', 'จำนวนเงินก่อนคิดภาษี',  55, 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +3 from apirequest), 3, 'serviceBillingDiscRate', 'Decimal', 'ส่วนลด %',  0, 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +4 from apirequest), 4, 'serviceBillingdiscAmt', 'Decimal', 'จำนวนส่วนลด',  0, 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +5 from apirequest), 5, 'serviceBillingVatRate', 'Decimal', 'ภาษี %',  7, 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +6 from apirequest), 6, 'serviceBillingVatAmt', 'Decimal', 'ภาษี',  3.85, 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +7 from apirequest), 7, 'serviceBillingNetAmt', 'Decimal', 'จำนวนเงินสุทธิ',  58.85, 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +8 from apirequest), 8, 'vatInclude', 'String', 'ภาษีรวมในมูลค่า',  'N', 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +9 from apirequest), 9, 'companyCode', 'String', 'รหัสบริษัท (ตัวพิมพ์ใหญ่)',  '''TESTER01''', 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +10 from apirequest), 10, 'serviceBillingServiceNetAmt', 'Decimal', '',  58.85, 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +11 from apirequest), 11, 'exchangeRate', 'Decimal', 'อัตราแลกเปลี่ยน',  1, 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +12 from apirequest), 12, 'exchageRateDate', 'String', 'วันที่อัตราแลกเปลี่ยน',  '''2024-05-02''', 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +13 from apirequest), 13, 'billAddress', 'String', '',  '''476 หมู่ที่ 4 ซอย 2บี ถนนสุขุมวิท ต.แพรกษา อ.เมืองสมุทรปราการ จ.สมุทรปราการ 10280''', 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +14 from apirequest), 14, 'billTName', 'String', '',  '''บริษัท เฟลตัล อุตสาหกรรม จำกัด''', 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +15 from apirequest), 15, 'divisionNo', 'String', 'รหัสสาขา',  '''00''', 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +16 from apirequest), 16, 'taxIdNo', 'String', 'หมายเลขประจำตัวผู้เสียภาษี',  '''0115531000684''', 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +17 from apirequest), 17, 'currencyCode', 'String', 'รหัสสกุลเงิน',  '''THB''', 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +18 from apirequest), 18, 'documentGroupCode', 'String', 'รหัสกลุ่มเอกสาร',  '''00''', 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +19 from apirequest), 19, 'customerMasterCode', 'String', 'รหัสลูกค้า',  '00000001', 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +20 from apirequest), 20, 'empCode', 'String', 'รหัสพนักงาน',  'J007', 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +21 from apirequest), 21, 'divisionCode', 'String', 'รหัสสาขา',  '00', 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +22 from apirequest), 22, 'sectionCode', 'String', 'รหัสแผนก',  '00', 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +23 from apirequest), 23, 'createByEmpCode', 'String', 'รหัสผู้สร้าง',  'ADMIN', 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +24 from apirequest), 24, 'audited', 'String', 'ตรวจสอบ',  'N', 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +25 from apirequest), 25, 'serviceBillingDueDate', 'String', 'วันที่ครบกำหนด',  '''2024-05-12''', 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +26 from apirequest), 26, 'updateReferByPrice', 'String', '',  'N', 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +27 from apirequest), 27, 'cusDivisionNo', 'String', 'สาขาลูกค้า', '00', 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +28 from apirequest), 28, 'jobCode', 'String', 'รหัสงาน',  '00', 'Y', 46, 'serviceBillingNoteDetailFilter', 'N');


INSERT INTO STRDBA.apirequest
(apirequestid, apino, "filter", typename, description, example, required, apimasterid, objectname, isarray)
VALUES
((select max(apirequestid) +1 from apirequest), 1, 'serviceCode', 'String', 'รหัส',  '''000000''', 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +2 from apirequest), 2, 'serviceUnit', 'String', '',  null, 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +3 from apirequest), 3, 'serviceVat', 'String', 'คิดภาษี',  ',''Y''', 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +4 from apirequest), 4, 'serviceQTY', 'String', 'จำนวน',  1, 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +5 from apirequest), 5, 'servicePrice', 'String', 'ราคาต่อหน่วย',  55, 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +6 from apirequest), 6, 'laborPrice', 'String', 'ราคาแรงงาน',  0, 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +7 from apirequest), 7, 'referenceDocument', 'String', 'เลขที่เอกสารอ้างอิง',  null, 'N', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +8 from apirequest), 8, 'quDocNo', 'String', 'เลขที่เอกสาร QU',  null, 'N', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +9 from apirequest), 9, 'soDocNo', 'String', 'เลขที่เอกสาร SO',  null, 'N', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +10 from apirequest), 10, 'periodNo', 'String', 'งวดที่',  0, 'N', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +11 from apirequest), 11, 'startPeriodDate', 'String', 'วันที่เริ่มต้นงวด',  '''''', 'N', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +12 from apirequest), 12, 'returnPayDate', 'String', 'วันที่คืนเงินชำระ',  '''''', 'N', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +13 from apirequest), 13, 'startNo', 'String', 'ลำดับเริ่มต้น',  0, 'N', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +14 from apirequest), 14, 'endNo', 'String', 'ลำดับสิ้นสุด',  0, 'N', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +15 from apirequest), 15, 'soDocIndex', 'String', 'แถวของ SO',  0, 'N', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +16 from apirequest), 16, 'typeSe', 'String', '',  '''N''', 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +17 from apirequest), 17, 'serviceDiscAmt', 'String', 'จำนวนส่วนลด',  0, 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +18 from apirequest), 18, 'serviceNetPrice', 'String', 'จำนวนเงินสุดธิ',  55, 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +19 from apirequest), 19, 'serviceReceiveCn', 'String', '',  0, 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +20 from apirequest), 20, 'serviceDiscRate', 'String', 'จำนวนส่วนลด',  0, 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +21 from apirequest), 21, 'companyCode', 'String', 'รหัสบริษัท (ตัวพิมพ์ใหญ่)',  '''TESTER01''', 'Y', 46, 'serviceBillingNoteDetailFilter', 'N'),
((select max(apirequestid) +22 from apirequest), 22, 'jobCode', 'String', 'รหัสงาน',  '''00''', 'Y', 46, 'serviceBillingNoteDetailFilter', 'N');
{
    "serviceBillingNoteMasterFilter": {
        "serviceBillingCreditTerm": 10,
        "serviceBillingTotal": 55,
        "serviceBillingDiscRate": 0,
        "serviceBillingdiscAmt": 0,
        "serviceBillingVatRate": 7,
        "serviceBillingVatAmt": 3.85,
        "serviceBillingNetAmt": 58.85,
        "vatInclude": "N",
        "companyCode": "TESTER01",
        "serviceBillingServiceNetAmt": 58.85,
        "exchangeRate": 1,
        "exchageRateDate": "2024-05-02",
        "billAddress": "476 หมู่ที่ 4 ซอย 2บี ถนนสุขุมวิท ต.แพรกษา อ.เมืองสมุทรปราการ จ.สมุทรปราการ 10280",
        "billTName": "บริษัท เฟลตัล อุตสาหกรรม จำกัด",
        "divisionNo": "00",
        "taxIdNo": "0115531000684",
        "currencyCode": "THB",
        "documentGroupCode": "00",
        "customerMasterCode": "00000001",
        "empCode": "J007",
        "divisionCode": "00",
        "sectionCode": "00",
        "createByEmpCode": "ADMIN",
        "audited": "N",
        "serviceBillingDueDate": "2024-05-12",
        "updateReferByPrice": "N",
        "cusDivisionNo": "00",
        "jobCode": "00"
    },
    "serviceBillingNoteDetailFilter": [
        {
            "serviceCode": "000000",
            "serviceUnit": "002",
            "serviceVat": "Y",
            "serviceQTY": 1,
            "servicePrice": 55,
            "laborPrice": 0,
            "referenceDocument": null,
            "quDocNo": "QU-XX-XXXX/XXXX",
            "soDocNo": "SO-XX-XXXX/XXXX",
            "periodNo": 0,
            "startPeriodDate": "",
            "returnPayDate": "",
            "startNo": 0,
            "endNo": 0,
            "soDocIndex": 0,
            "typeSe": "N",
            "serviceDiscAmt": 0,
            "serviceNetPrice": 55,
            "serviceReceiveCn": 0,
            "serviceDiscRate": 0,
            "companyCode": "TESTER01",
            "jobCode": "00",
        }
    ]    
}
