POS deliveryordermaster change exchagerate to exchangerate


INSERT INTO "STRDBA".apirequest
(apirequestid, apino, "filter", typename, description, example, required, apimasterid, objectname, isarray)
VALUES
((select max(apirequestid) +1 from apirequest), 1, 'doCreditTerm', 'Integer', 'จำนวนวันที่ครบกำหนดชำระ', 20, 'Y', 49, 'deliveryOrderMasterFilter', 'N'),
((select max(apirequestid) +2 from apirequest), 2, 'doTotal', 'Decimal', 'จำนวนเงิน', 4132.5, 'Y', 49, 'deliveryOrderMasterFilter', 'N'),
((select max(apirequestid) +3 from apirequest), 3, 'doDiscRate', 'Decimal', 'อัตราส่วนลด', 0, 'Y', 49, 'deliveryOrderMasterFilter', 'N'),
((select max(apirequestid) +4 from apirequest), 4, 'doDiscAmt', 'Decimal', 'จำนวนส่วนลด', 0, 'Y', 49, 'deliveryOrderMasterFilter', 'N'),
((select max(apirequestid) +5 from apirequest), 5, 'doDepositNo', 'String', 'เลขที่เอกสารมัดจำรับ', 'DR-XX-XXXX/XXXX', 'Y', 49, 'deliveryOrderMasterFilter', 'N'),
((select max(apirequestid) +6 from apirequest), 6, 'doDepositAmt', 'Decimal', 'จำนวนเงินมัดจำรับ', 0, 'Y', 49, 'deliveryOrderMasterFilter', 'N'),
((select max(apirequestid) +7 from apirequest), 7, 'doVatRate', 'Decimal', 'อัตราภาษี', 7, 'Y', 49, 'deliveryOrderMasterFilter', 'N'),
((select max(apirequestid) +8 from apirequest), 8, 'doVatAmt', 'Decimal', 'ภาษี', 0, 'Y', 49, 'deliveryOrderMasterFilter', 'N'),
((select max(apirequestid) +9 from apirequest), 9, 'doNetAmt', 'Decimal', 'จำนวนเงินสุทธิ', 4132.5, 'Y', 49, 'deliveryOrderMasterFilter', 'N'),
((select max(apirequestid) +10 from apirequest), 10, 'vatInclude', 'String', 'ภาษีรวมในมูลค่า', 'N', 'Y', 49, 'deliveryOrderMasterFilter', 'N'),
((select max(apirequestid) +11 from apirequest), 11, 'companyCode', 'String', 'รหัสบริษัท (ตัวพิมพ์ใหญ่)', 'TESTER01', 'Y', 49, 'deliveryOrderMasterFilter', 'N'),
((select max(apirequestid) +12 from apirequest), 12, 'doProdNetAmt', 'Decimal', 'จำนวนเงินสุทธิ', 4132.5, 'Y', 49, 'deliveryOrderMasterFilter', 'N'),
((select max(apirequestid) +13 from apirequest), 13, 'exchangeRate', 'Decimal', 'อัตราแลกเปลี่ยน', 1, 'Y', 49, 'deliveryOrderMasterFilter', 'N'),
((select max(apirequestid) +14 from apirequest), 14, 'exchangeRateDate', 'String', 'วันที่อัตราแลกเปลี่ยน', '2024-04-25', 'Y', 49, 'deliveryOrderMasterFilter', 'N'),
((select max(apirequestid) +15 from apirequest), 15, 'doWithHodingTax', 'Decimal', 'ภาษีหัก ณ ที่จ่าย', 0, 'Y', 49, 'deliveryOrderMasterFilter', 'N'),
((select max(apirequestid) +16 from apirequest), 16, 'divisionNo', 'String', 'สาขาของลูกค้า', '00', 'Y', 49, 'deliveryOrderMasterFilter', 'N'),
((select max(apirequestid) +17 from apirequest), 17, 'taxIdNo', 'String', 'หมายเลขประจำตัวผู้เสียภาษี', '0135550001445', 'Y', 49, 'deliveryOrderMasterFilter', 'N'),
((select max(apirequestid) +18 from apirequest), 18, 'doDueDate', 'Integer', 'วันที่ครบกำหนด', 20, 'Y', 49, 'deliveryOrderMasterFilter', 'N'),
((select max(apirequestid) +19 from apirequest), 19, 'currencyCode', 'String', 'รหัสสกุลเงิน', 'THB', 'Y', 49, 'deliveryOrderMasterFilter', 'N'),
((select max(apirequestid) +20 from apirequest), 20, 'documentGroupCode', 'String', 'รหัสกลุ่มลูกค้า', '00', 'Y', 49, 'deliveryOrderMasterFilter', 'N'),
((select max(apirequestid) +21 from apirequest), 21, 'custCode', 'String', 'รหัสลูกค้า', '00000001', 'Y', 49, 'deliveryOrderMasterFilter', 'N'),
((select max(apirequestid) +22 from apirequest), 22, 'empCode', 'String', 'รหัสพนักงาน', 'J007', 'Y', 49, 'deliveryOrderMasterFilter', 'N'),
((select max(apirequestid) +23 from apirequest), 23, 'divisionCode', 'String', 'รหัสสาขา', '00', 'Y', 49, 'deliveryOrderMasterFilter', 'N'),
((select max(apirequestid) +24 from apirequest), 24, 'sectionCode', 'String', 'รหัสแผนก', '00', 'Y', 49, 'deliveryOrderMasterFilter', 'N'),
((select max(apirequestid) +25 from apirequest), 25, 'createByEmpCode', 'String', 'รหัสผู้สร้างเอกสาร', 'ADMIN', 'Y', 49, 'deliveryOrderMasterFilter', 'N'),
((select max(apirequestid) +26 from apirequest), 26, 'dueDate', 'String', 'วันที่ครบกำหนด', '2024-06-01', 'Y', 49, 'deliveryOrderMasterFilter', 'N'),
((select max(apirequestid) +27 from apirequest), 27, 'depositVat', 'String', 'ถาษีมัดจำ', '', 'Y', 49, 'deliveryOrderMasterFilter', 'N'),
((select max(apirequestid) +28 from apirequest), 28, 'checkLot', 'String', 'ใช้ระบบ Lot', 'N', 'Y', 49, 'deliveryOrderMasterFilter', 'N'),
((select max(apirequestid) +29 from apirequest), 29, 'vatDrs', 'String', 'ภาษีของมัดจำ', '0', 'Y', 49, 'deliveryOrderMasterFilter', 'N'),
((select max(apirequestid) +30 from apirequest), 30, 'vatRateDrs', 'String', 'อัตราภาษีของมัดจำ', null, 'Y', 49, 'deliveryOrderMasterFilter', 'N'),
((select max(apirequestid) +31 from apirequest), 31, 'amountDrs', 'String', 'จำนวนมัดจำ', '', 'Y', 49, 'deliveryOrderMasterFilter', 'N'),
((select max(apirequestid) +32 from apirequest), 32, 'vatIncludeDrs', 'String', 'ภาษีรวมอยู่ในมัดจำ', '', 'Y', 49, 'deliveryOrderMasterFilter', 'N'),
((select max(apirequestid) +33 from apirequest), 33, 'jobCode', 'String', '', '00', 'Y', 49, 'deliveryOrderMasterFilter', 'N');


INSERT INTO "STRDBA".apirequest
(apirequestid, apino, "filter", typename, description, example, required, apimasterid, objectname, isarray)
VALUES
((select max(apirequestid) +1 from apirequest), 1, 'prodCode', 'String', 'รหัสสินค้า', '000000003', 'ํY', 43, 'deliveryOrderDetailFilter', 'N'),
((select max(apirequestid) +2 from apirequest), 2, 'whCode', 'String', 'รหัสคลังสินค้า', '00', 'Y', 43, 'deliveryOrderDetailFilter', 'N'),
((select max(apirequestid) +3 from apirequest), 3, 'prodVat', 'String', 'สินค้าคิดภาษี', 'N', 'Y', 43, 'deliveryOrderDetailFilter', 'N'),
((select max(apirequestid) +4 from apirequest), 4, 'prodConvFactor', 'Decimal', 'ตัวคูณ', 1, 'Y', 43, 'deliveryOrderDetailFilter', 'N'),
((select max(apirequestid) +5 from apirequest), 5, 'prodQTY', 'Decimal', 'จำนวนสินค้า', 1, 'Y', 43, 'deliveryOrderDetailFilter', 'N'),
((select max(apirequestid) +6 from apirequest), 6, 'prodPrice', 'Decimal', 'ราคาสินค้า', 4750, 'Y', 43, 'deliveryOrderDetailFilter', 'N'),
((select max(apirequestid) +7 from apirequest), 7, 'prodDiscRate0', 'String', 'อัตราส่วนลด', '13%', 'Y', 43, 'deliveryOrderDetailFilter', 'N'),
((select max(apirequestid) +8 from apirequest), 8, 'prodDiscAmt', 'Decimal', 'จำนวนส่วนลด', 617.5, 'Y', 43, 'deliveryOrderDetailFilter', 'N'),
((select max(apirequestid) +9 from apirequest), 9, 'prodNetPrice', 'Decimal', 'ราคาสินค้าสุทธิ', 4132.5, 'Y', 43, 'deliveryOrderDetailFilter', 'N'),
((select max(apirequestid) +10 from apirequest), 10, 'prodBaseQTY', 'Decimal', 'จำนวนสินค้าสุทธิ', 1, 'Y', 43, 'deliveryOrderDetailFilter', 'N'),
((select max(apirequestid) +11 from apirequest), 11, 'sendDate', 'String', 'วันที่ส่ง', '2024-04-25', 'N', 43, 'deliveryOrderDetailFilter', 'N'),
((select max(apirequestid) +12 from apirequest), 12, 'companyCode', 'String', 'รหัสบริษัท (ตัวพิมพ์ใหญ่)', 'TESTER01', 'Y', 43, 'deliveryOrderDetailFilter', 'N'),
((select max(apirequestid) +13 from apirequest), 13, 'unitCode', 'String', 'รหัสหน่วยนับ', '002', 'Y', 43, 'deliveryOrderDetailFilter', 'N'),
((select max(apirequestid) +14 from apirequest), 14, 'jobCode', 'String', 'รหัสงาน', '00', 'Y', 43, 'deliveryOrderDetailFilter', 'N');

[
  {
    "deliveryOrderMasterFilter": {
      "doDocDate": "2024-04-25",
      "doCreditTerm": 20,
      "doTotal": 4132.5,
      "doTotalNoVat": 4132.5,
      "doDiscRate": 0,
      "doDiscAmt": 0,
      "doDepositNo": "",
      "doDepositAmt": 0,
      "doVatRate": 7,
      "doVatAmt": 0,
      "doNetAmt": 4132.5,
      "charge": 0,
      "vatInclude": "N",
      "companyCode": "TESTER01",
      "doProdNetAmt": 4132.5,
      "exchangeRate": 1,
      "exchageRateDate": "2024-04-25",
      "doWithHodingTax": 0,
      "doBillAddress": "บ้านเลขที่ 2/3 หมู่ที่ 4 ต.เกาะไร่ อ.บ้านโพธิ์ จ.ฉะเชิงเทรา 24140",
      "divisionNo": "00",
      "taxIdNo": "0135550001445",
      "doDueDate": 20,
      "currencyCode": "THB",
      "documentGroupCode": "00",
      "custCode": "00000001",
      "empCode": "J007",
      "divisionCode": "00",
      "sectionCode": "00",
      "createByEmpCode": "ADMIN",
      "dueDate": "2024-05-15",
      "doBillTName": "บริษัท สยามบรรจุภัณฑ์ 45 จำกัด",
      "depositVat": "",
      "checkLot": "N",
      "vatDrs": "0",
      "vatRateDrs": null,
      "amountDrs": "",
      "vatIncludeDrs": "",
      "billingDate": "2024-05-15",
      "jobCode": "00"
    },
    "deliveryOrderDetailFilter": [
      {
        "prodCode": "000000003",
        "whCode": "00",
        "prodVat": "N",
        "accountCodeIncome": 214865,
        "accountCodeId": 214810,
        "accountCodeId2": 214870,
        "prodConvFactor": 1,
        "prodQTY": 1,
        "prodPrice": 4750,
        "prodDiscRate0": "13%",
        "prodDiscAmt": 617.5,
        "prodNetPrice": 4132.5,
        "prodTotalNetPrice": 4132.5,
        "prodBaseQTY": 1,
        "sendDate": "2024-04-25",
        "companyCode": "TESTER01",
        "unitCode": "002",
        "jobCode": "00"
      }
    ],
    "deliveryOrderReceiveFilter": {
      "deliveryOrderReceiveId": null,
      "doDocNo": null,
      "cashAmt": 4132.5,
      "bankRemark": null,
      "bankAmt": 0,
      "companyCode": "TESTER01",
      "chqNoOne": null,
      "chqAmtOne": 0,
      "chqNoTwo": null,
      "chqAmtTwo": 0,
      "chqRemark": null,
      "receiveChequeNoOne": null,
      "receiveChequeNoTwo": null,
      "creditNumber": null,
      "edcNumber": null,
      "creditbyBank": null,
      "creditAmt": 0
    },
    "otherPaymentFilter": []
  }
]